### ISSUE TITLE
No respose after click "Add action"

### ISSUE THREAD

**Issue by LipingMao** [ciscopipeline/Documentation#1]
Hi Team, 

I want to try ciscopipeline to create a backend for spark bot.
But when I try register a bot backend on ciscopipeline, there is no response after I click "add action".
There is no error, but just no response. I tried use different browser but get same issue.
Any one can help?

Thanks.
Liping Mao

**Comment by vallard** [comment]
Hi @LipingMao yeah, we've definitely had some issues with the front end.  Thanks for your comment.  Can you tell us:  Were you updating a bot or creating a brand new one? What browsers did you try?  What OS? The add-action is for static actions.  Perhaps trying the code backend would be more successful.  Really sorry about this.  Will try to update code this week with bug fixes.

**Comment by LipingMao** [comment]
@vallard 
Sorry, I did not make my test steps clear.
For your questions:
> Were you updating a bot or creating a brand new one?
The error happened in creating a brand new bot.

> What browsers did you try?
I tried in Safari and Firefox.

> What OS?
I'm using Mac OS (10.10.5)

Here is my detailed steps:
1. I register bot with in https://developer.ciscospark.com, the bot name is limaofirstbot, I record my access token.
2. I try register backend in https://ciscopipeline.io, I clieck the link:
"Step 4.Click here to create a new sparkbot backend!"
I file my bot name "limaofirstbot", token.
But when I create "Static Actions", there is no response after I click the green "Add Action" button.

Please let me know if I miss anythin. Thanks.

**Comment by vallard** [comment]
Dang!  Yeah, just tried it.  I thought that I had tested that.  I'll fix it
today.  Sorry about that.

**Comment by vallard** [comment]
I updated the page with the fix.  It should work now.  Big apologies for that.  That was a simple oversight.  Need to look into doing automated front end testing.

**Comment by vallard** [comment]
Let me know if it works for you and I'll close the issue.  Thanks again for bringing this to our attention.

**Comment by LipingMao** [comment]
@vallard ， Thanks for your quick help, I bring my "first" helloworld bot up in spark room now. Please help to close this issue.
