### ISSUE TITLE
getting error saying I cannot have more than 5 bots but I have less

### ISSUE THREAD

**Issue by rivimont** [ciscopipeline/Documentation#3]
I had another idea for a bot. When I login, I saw that I only have 3 bots. However, when trying to add another one I get the message:
" Bad Request: Sorry awesome power user. You can not have more than 5 bots."

I even tried getting rid of one of my bots (so down to 2), but get the same error message.

**Comment by vallard** [comment]
Ah, yes, I have to fix the delete function.  Sorry that has been something
I need to do.  Will get on it.

**Comment by vallard** [comment]
Fixed now.
