### ISSUE TITLE
dial tcp: lookup api.ciscospark.com timeout

### ISSUE THREAD

**Issue by LipingMao** [ciscopipeline/Documentation#4]
Hi Ciscopipline,

My bot-limao can't work today,it worked before, I see some timeout log, then I re-create it, but get the following error log:

 Invalid: Probably a bad Spark Token Get https://api.ciscospark.com/v1/people/me: dial tcp: lookup api.ciscospark.com on 10.32.0.10:53: read udp 10.215.1.24:56206->10.32.0.10:53: i/o timeout

I'm sure my Token is right, and I even tried re-generate a token.

**Comment by vallard** [comment]
Yeah, I am having some problems with Pipeline.  We had a crash last night,
still trying to get to root cause.  Will try to have it up tomorrow.
Thanks for your patience!

**Comment by LipingMao** [comment]
@vallard  thanks for the info!

**Comment by LipingMao** [comment]
@vallard any luck on that? I tried re-create bot, looks like still unlucky now ;-)

**Comment by vallard** [comment]
Still working on it!  Hope to get it back up next week!  So sorry.

**Comment by vallard** [comment]
Ok, should be up again.  Sorry for the delay.  I don't have a way to automatically restart the bots yet, but if you go in and edit your bot, don't change anything, and just hit save changes it will restart it. Really sorry about that.

**Comment by vallard** [comment]
We changed to a brand new kubernetes cluster with more capacity so we should do much better now.

**Comment by LipingMao** [comment]
@vallard  Thanks , it works for me now.
